# This workflow builds a Java project using Gradle.

name: Java CI with Gradle

# Defines when the workflow should run.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Defines the jobs in the workflow.
jobs:

  # Build job
  build:

    # Use the latest Ubuntu runner provided by GitHub.
    runs-on: ubuntu-latest

    permissions:
      contents: read

    # Steps executed in the build job.
    steps:

    # Get the repository code into the GitHub runner.
    - uses: actions/checkout@v4

    # Set up Java JDK 17.
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Give execute permission to the Gradle Wrapper.
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # Build the Java project using the Gradle Wrapper.
    - name: Build with Gradle Wrapper
      run: ./gradlew build


  # Dependency submission job
  dependency-submission:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

    # Get the repository code into the runner.
    - uses: actions/checkout@v4

    # Set up Java JDK 17.
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generate and submit the project's dependency graph.
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
